name: Build EXE and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PyInstaller
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: pyinstaller.spec
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/windows/tise.exe
